name: LanguageWire API - CI

on:
  pull_request:
    merge_group:
      branches:
        - master

jobs:
  build:

    name: API Tests

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.12.2
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: export PYTHONPATH=$PWD && pytest
